export const menuData = {
  tastingFlights: [
    {
      name: 'La Rafale',
      description: '4 x 12,5 cl au choix parmi les cidres et poirés au fût',
      price: 15,
    },
    {
      name: 'La Grande Valse',
      description: '14 x 12,5 cl – La totalité de la carte',
      price: 45,
    },
    {
      name: 'La Farandole de calvas',
      description: '4 x 2 cl au choix parmi les eaux-de-vie et calvados',
      price: 20,
    },
  ],
  beers: [
    { name: 'Redor Pils (Dupont)', description: '5% - Blonde légère', price: 3 },
    { name: 'Saison Dupont Bio (Dupont)', description: '5.5% - Saison', price: 4.5 },
    { name: 'Petit Boulba Bio (La Senne)', description: '2.8% - Session IPA', price: 4.5 },
    { name: 'Jambe de Bois Bio (La Senne)', description: '8% - Triple', price: 5.5 },
    { name: 'Blanche de Lessive Bio (La Lesse)', description: '5% - Blanche', price: 5 },
    { name: 'Holy IPA (Novabirra)', description: '6.5% - Belgian IPA', price: 6.5 },
    { name: 'Franc Belge (De Ranke)', description: '5.2% - Spéciale Ambrée', price: 5.5 },
    { name: 'Orval (Orval)', description: '6.2% - Trappiste', price: 6 },
    { name: 'Moose Milk Stout (L\'Annexe)', description: '6.5% - Stout crémeuse', price: 6.5 },
    { name: 'Trottinette (DrinkDrink!)', description: '0% - Alcohol-free IPA', price: 6 },
  ],
  wines: [
    {
      name: 'Saint-Chinian Bio (Domaine des Soulié)',
      description: 'Cinsault, syrah, grenache - Rouge - Rond équilibré',
      glassPrice: 5,
      bottlePrice: 25,
    },
    {
      name: 'Vénus (Pinchinat)',
      description: 'Vermentino Bio - Blanc - Sec et fruité',
      glassPrice: 5,
      bottlePrice: 25,
    },
  ],
  nonAlcoholic: [
    { name: 'Jus de pomme (Fruitdas, BE)', size: '25cl', price: 3 },
    { name: 'Jus Pomme-Coing (Fruitdas, BE)', size: '25/33cl', price: '3/4' },
    { name: 'Pétillant de poire-rhubarbe 0% (Fruitdas, BE)', size: '33cl', price: 6 },
    { name: 'Pétillant de pomme 0% (Fruitdas, BE)', size: '33cl', price: 5 },
    { name: 'Cidre 0.5% - sidra sin alcohol (Trabanco, ES)', size: '33cl', price: 6 },
    { name: 'Limonade naturelle Basilic (Cuarenta, BXL)', size: '33cl', price: 5 },
    { name: 'Limonade naturelle Gingembre (Cuarenta, BXL)', size: '33cl', price: 5 },
    { name: 'Cola Ritchie (BE)', size: '27.5cl', price: 3.5 },
    { name: 'Kéfir du moment (Originals Kéfir, 1030 BXL)', size: '25cl', price: 6 },
    { name: 'Café (Winok, 1030 BXL) French press', size: '', price: 2.5 },
    { name: 'Thés & Infusions (du jardin ou L\'Heure Bleue)', size: '', price: 3.5 },
    { name: 'Eau pétillante (Gintsberg, BE)', size: '20cl', price: 1.5 },
    { name: 'Eau communale (Château du Robinet, BE)', size: 'Verre', price: 0 },
  ],
  ratafia: [
    {
      name: 'Ratafia de Cidre (Les Bulles Ardennaises) 18%',
      description: 'Vieilli 3 ans dont 6 mois en fût de chêne',
      price: 7,
    },
    {
      name: 'Ratafia de Poiré (Les Bulles Ardennaises) 18%',
      description: 'Vieilli 3 ans dont 6 mois en fût de chêne',
      price: 8,
    },
    {
      name: 'Pommeau de Bretagne AOP (François Séhédic) 17.5%',
      description: '8 ans en fût de chêne. Notes de fruits cuits, pruneaux',
      price: 9,
    },
    {
      name: 'Forestic Blanc (François Séhédic) 17%',
      description: '8 ans en chêne épuisé. Une seule variété de pomme (Guillevic)',
      price: 13,
    },
  ],
  spirits: [
    { name: 'Eau de Vie de Poiré (Pacory) 44%', description: 'Blanche non vieillie', price: 8 },
    { name: 'La Drôlerie (Damien Lemasson) 46%', description: 'Eau de vie de cidre blanche', price: 8 },
    { name: 'Eau-de-vie de Coing (Atelier Constant-Berger) 40%', description: 'Blanche non vieillie 100% coing', price: 15 },
    { name: 'Ardennos (Les Bulles Ardennaises) 42%', description: '3 ans en fût de chêne', price: 9 },
    { name: 'Fine Calvados (Damien Lemasson) 42%', description: '3 ans en fût de chêne', price: 10 },
    { name: 'Fine Bretagne Bio AOC (François Séhédic) 42%', description: '12 ans en fût de chêne', price: 14 },
    { name: 'Calvados Domfrontais AOC (Pacory) 42%', description: '12 ans en fût de chêne. Poire et pomme', price: 14 },
    { name: 'Condreau (Cidrerie du Condroz) 42%', description: 'Le calva Belge. 3 ans en fût de chêne', price: 11 },
  ],
  food: [
    { name: 'Popcorn (salé)', price: 2 },
    { name: 'Popcorn + caramel au beurre salé', price: 3 },
    { name: 'Caviar d\'aubergines (avec pain)', price: 10 },
    { name: 'Crème de poivrons rouges anciens doux (avec pain)', price: 10 },
    { name: 'Demi-camembert rôti au four (avec pommes de terre)', price: 12 },
    { name: 'La planche de fromages des terroirs cidricoles (avec pain)', price: 16 },
    { name: 'Portion de fromage du moment', price: 6 },
    { name: 'Saucisson de porc Entier', price: 8 },
    { name: 'Saucisson de porc Demi', price: 4 },
    { name: 'Saucisse sèche des Moutons de Bruxelles', price: 8 },
    { name: 'Pâté de campagne au poivre vert et eau de vie 190g (avec pain)', price: 12 },
    { name: 'Rillettes Bretonnes de porc au cidre 190g (avec pain)', price: 12 },
  ],
  galettes: [
    { name: '2 ingrédients', price: 11 },
    { name: '3 ingrédients', price: 12 },
    { name: '4 ingrédients', price: 13 },
  ],
  dessert: {
    name: 'Caramel au beurre salé (maison)',
    price: 7,
  },
};
